course = "  Python Programming"
print(course.upper())
print(course.lower())
print(course.title())
print(course.strip())
print(course.lstrip())
print(course.rstrip())
print(course.find("Pro"))
print(course.replace("Python", "JavaScript"))
print("Python" in course)
print("Java" not in course)